sudo: required

language: ruby

services:
  - docker

install:
  - bundle install
  - rake -f ci/Rakefile ci:pull

script: rake -f ci/Rakefile ci:run

matrix:
  include:
    - name: "Ruby 2.5.1 with MXNet 1.2.1.post1 on Python 3.7.0"
      env:
        - ruby_version=2.5.1
        - python_version=3.7.0
        - mxnet_version=1.2.1.post1

    - name: "Ruby 2.4.4 with MXNet 1.2.1.post1 on Python 3.7.0"
      env:
        - ruby_version=2.4.4
        - python_version=3.7.0
        - mxnet_version=1.2.1.post1

    - name: "Ruby 2.3.7 with MXNet 1.2.1.post1 on Python 3.7.0"
      env:
        - ruby_version=2.3.7
        - python_version=3.7.0
        - mxnet_version=1.2.1.post1
